"""Module for config constants."""

COLLECTION_NAME = "rca-knowledge-base"
DEFAULT_EMBEDDING_MODEL = "BAAI/bge-m3"
DEFAULT_JIRA_URL = "https://issues.redhat.com"
DEFAULT_JIRA_PROJECTS = {
    "OSP",
    "OSPCIX",
    "OSPRH",
}
DEFAULT_CHUNK_SIZE = 1024
DEFAULT_MAX_RESULTS = 10000
JIRA_YEAR_OFFSET = 0
DEFAULT_NUM_SCRAPER_PROCESSES=10
